# Тема “Вычисления с помощью Numpy”

## Задание 1

In [24]:
import numpy as np

a = ([1, 6], [2, 8], [3, 11], [3, 10], [1, 7])
b = np.array(a)
b

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [25]:
mean_a = b.mean(axis = 0)

In [26]:
mean_a

array([2. , 8.4])

In [27]:
b

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

## Задание  2

In [28]:
a_centered = b - mean_a

In [29]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3

In [16]:
N = 5

In [17]:
a_centered[:, 0]

array([-1.,  0.,  1.,  1., -1.])

In [18]:
a_centered[:, 1]

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [19]:
a_centered_sp_1 = np.dot(a_centered[:, 0], a_centered[:, 1])/(N-1)

## Задание 4

In [20]:
a_centered_sp_2 = np.cov(b.transpose())

In [21]:
a_centered_sp_1 == a_centered_sp_2[0][1]

True

# Тема “Работа с данными в Pandas”

## Задание 1

In [115]:
import pandas as pd

In [116]:
data_1 = {'author_id' : [1, 2, 3],
        'author_name' : ['Тургенев', 'Чехов', 'Островский']}
authors = pd.DataFrame(data_1)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [117]:
data_2 = {'author_id' : [1, 1, 1, 2, 2, 3, 3],
        'book_title' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
        'price' : [450, 300, 350, 500, 450, 370, 290]}
price = pd.DataFrame(data_2, columns=['author_id', 'book_title', 'price'])
price

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

## Задание 2

In [118]:
authors_price = pd.merge(authors, price)
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Задание 3

In [123]:
top5 = authors_price.sort_values(by=['price'], ascending = False).head(5)
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

## Задание 4

In [203]:
authors_stat_data  = {'author_name' : authors['author_name'],
        'min_price' : [authors_price[(authors_price['author_name'] == i)]['price'].min() for i in authors_price['author_name'].unique()],
        'max_price' : [authors_price[(authors_price['author_name'] == i)]['price'].max() for i in authors_price['author_name'].unique()],
        'mean_price' : [round(authors_price[(authors_price['author_name'] == i)]['price'].mean()) for i in authors_price['author_name'].unique()]}
authors_stat = pd.DataFrame(authors_stat_data)
authors_stat

author_name  min_price  max_price  mean_price
0    Тургенев        300        450         367
1       Чехов        450        500         475
2  Островский        290        370         330

## Задание 5